virtual_machines:

  windows:
    socket: /pcgrande/Desarrollo/vfio-pcgrande/i915ovmf-archivos/qmp-sock
    delay: 1
    hubs:
      - xhci0.0
      - xhci1.0
    ports:
      - /devices/pci0000:00/0000:00:14.0/usb1/1-2
      - /devices/pci0000:00/0000:00:14.0/usb2/2-3
      - /devices/pci0000:00/0000:00:14.0/usb1/1-3