OVMF_CODE=$OVMF/OVMF_CODE.manu.fd
OVMF_VARS=$OVMF/vars/macOS_VARS.fd
OVMF_OPREG=$OVMF/opregion.bin
OVMF_BDSM=$OVMF/bdsmSize.bin
NVIDIA_VBIOS=$OVMF/vbios_10de_1299_1.rom
INTEL_GVTD_BIOS=$OVMF/i915ovmf.rom
SSDT_BATERIAFALSA=$OVMF/ssdt1.dat
HOTPLUG_QMPSOCK=$OVMF/qmp-sock
