#!/bin/bash -x
## SCRIPT PARA PREPARAR GUEST EN MODO VFIO
## FECHA: 9 de mayo de 2023

if [ -z $1 ]; then
	exit 1
fi

function intel_gpu(){
	systemctl stop display-manager.service
	sleep 1
	for i in $(lsof | grep -w i915 | cut -d " " -f 1 | tr "\n" " "); do
		killall "$i"
	done
}

VFIO_CONF_DEV_DIR="/usr/local/etc/vfio/devices/$1"

for i in $VFIO_CONF_DEV_DIR/*; do
	source $i
	if [[ "$DRIVER" == "i915" ]]; then
		intel_gpu
	fi
	echo "$VENDOR $DEVICE" > "/sys/bus/pci/drivers/vfio-pci/new_id"
	echo "0000:$BUS:$SLOT.$FUNC" > "/sys/bus/pci/drivers/$DRIVER/unbind"
	echo "0000:$BUS:$SLOT.$FUNC" > "/sys/bus/pci/drivers/vfio-pci/bind"
	sleep 0.5

done
