#!/bin/bash
## NUEVO SCRIPT PARA CONTROLAR PASSTHROUGH EN LIBVIRT
## FECHA: 9 de mayo de 2023

## VARIABLES

MAQUINA_VM=$1
BOARD_NAME=$(cat /sys/devices/virtual/dmi/id/board_name)
NUM_IOMMU=$(ls -1v /sys/kernel/iommu_groups/ | tail -n 1)
VFIO_CONF_DIR="/usr/local/etc/vfio/"
VFIO_CONF_VM_DIR="$VFIO_CONF_DIR/qemuhooks"

## FUNCIONES AUXILIARES
function error(){
	RED='\033[1;31m'
	NC='\033[0m'
	printf "${RED}[ERROR] $@ ${NC}\n"
}

function info(){
	BLUE='\033[1;36m'
	NC='\033[0m'
	printf "${BLUE}[INFO] $@ ${NC}\n"
}

function ayuda(){
	info "USO: $0 [nombre-de-dominio-o-vm] [-p|--prepare|-r|--release]"
}

function generar_conf(){
	cp "${VFIO_CONF_VM_DIR}/_sample.conf" "${VFIO_CONF_VM_DIR}/${MAQUINA_VM}_${BOARD_NAME}.conf"
	sed -i "s#replaceme#${MAQUINA_VM}#g" "${VFIO_CONF_VM_DIR}/${MAQUINA_VM}_${BOARD_NAME}.conf"
	sed -i "s#replace-me2#${BOARD_NAME}#g" "${VFIO_CONF_VM_DIR}/${MAQUINA_VM}_${BOARD_NAME}.conf"
	sed -i "s#re-placeme3#${HOSTNAME}#g" "${VFIO_CONF_VM_DIR}/${MAQUINA_VM}_${BOARD_NAME}.conf"

}

## COMPROBACIÓN: DOS ARGUMENTOS
if [[ $1 == "-h" ]]; then
	ayuda
	exit 1
fi


if [ $# -lt 2 ]; then
	error "Faltan argumentos."
	ayuda
	echo ""
	exit 1
fi

## COMPROBACIÓN: PREPARE O RELEASE
VFIO_BIND=-1
if [[ $2 == "--prepare" ]] || [[ $2 == "-p" ]]; then
	VFIO_BIND=1
elif [[ $2 == "--release" ]] || [[ $2 == "-r" ]]; then
	VFIO_BIND=0
elif [[ $2 == "-n" ]]; then
	generar_conf
	nano "${VFIO_CONF_VM_DIR}/${MAQUINA_VM}_${BOARD_NAME}.conf"
	exit 0
else
	error "Has puesto $2. Tienes que poner --prepare (-p) o --release (-r) como segundo argumento."
	ayuda
	echo ""
	exit 1
fi

## COMPROBACIÓN: NOMBRE DE MÁQUINA VIRTUAL CORRECTO
#if ! virsh --connect qemu:///system list --all --name | grep $1 >/dev/null; then
#	error "La máquina virtual $1 no existe. Prueba con:"
#	virsh list --all --name
#	exit 1
#fi

## GENERAR CONFIGURACIÓN PARA UNA NUEVA VM
if [ ! -f "${VFIO_CONF_VM_DIR}/${MAQUINA_VM}_${BOARD_NAME}.conf" ]; then
	generar_conf
fi

source "$VFIO_CONF_VM_DIR/${MAQUINA_VM}_${BOARD_NAME}.conf"

for ((i=0; i<$NUM_IOMMU+1; i++)); do
	printf -v j "%02d" $i
	IO_SEL="IOMMU_$j"

	if [[ ${!IO_SEL} == 1 ]]; then
		if [ $VFIO_BIND -eq 1 ]; then
			info "Grupo IOMMU $i entrando en modo VFIO."
			/usr/local/bin/vfio-prepare $i
		elif [ $VFIO_BIND -eq 0 ]; then
			info "Grupo IOMMU $i saliendo de modo VFIO"
			/usr/local/bin/vfio-release $i
		else
			error "Problemas al determinar el modo de funcionamiento (prepare o release)"
			exit 1
		fi
	fi
done

## COSAS A HACER EN TODAS LAS MÁQUINAS AL INICIARLAS (hugepages, governor, etc.)
info "Ejecutando otras configuraciones..."
if [ $VFIO_BIND -eq 1 ]; then
	vfio-alloc-hugepages
	vfio-cpumode-perf
elif [ $VFIO_BIND -eq 0 ]; then
	vfio-dealloc-hugepages
	vfio-cpumode-ondemand
else
	error "Problemas al determinar el modo de funcionamiento (prepare o release)"
        exit
fi
