#!/bin/bash

export DISPLAY=:0.0
export XDG_SESSION_DESKTOP=xubuntu
export XDG_CURRENT_DESKTOP=XFCE
export XDG_SESSION_TYPE=x11
export DESKTOP_SESSION=xubuntu
export XDG_SESSION_CLASS=user
export DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/1000/bus

xfce4-session-logout -lf
